version: '3.8'

services:
  postgres:
    container_name: pg_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER:-example}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
    volumes:
      - postgres:/data/postgres
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
