version: '3.8'

services:
  postgres:
    container_name: pg_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-example}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
